"""Data models for Authorization Firewall, Canonical Transactions, Rules, and Decisions."""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
from enum import Enum
from datetime import datetime


class DecisionEnum(str, Enum):
    ALLOW = "ALLOW"
    CHALLENGE = "CHALLENGE"
    DENY = "DENY"


class RuleImpactEnum(str, Enum):
    ALLOW = "ALLOW"
    CHALLENGE = "CHALLENGE"
    DENY = "DENY"


class RuleOutcome(BaseModel):
    rule_name: str
    passed: bool
    decision_impact: RuleImpactEnum
    reason: str
    details: Optional[Dict[str, Any]] = None


class AgentProposal(BaseModel):
    """The original intent/proposal formed by the AI Buyer Agent."""
    sku: str
    title: str
    merchant_id: str
    category: str
    unit_price_inr: float
    quantity: int = 1
    estimated_total_inr: float
    currency: str = "INR"
    destination_pincode: Optional[str] = None
    recurring: bool = False


class CanonicalTransaction(BaseModel):
    """The final, executable transaction facts submitted to the deterministic firewall."""
    transaction_id: str
    principal_id: str
    agent_id: str
    merchant_id: str
    sku: str
    category: str
    quantity: int = 1
    unit_price_inr: float = Field(..., ge=0)
    subtotal_inr: float = Field(..., ge=0)
    discount_inr: float = Field(default=0.0, ge=0)
    tax_inr: float = Field(default=0.0, ge=0)
    shipping_inr: float = Field(default=0.0, ge=0)
    total_inr: float = Field(..., ge=0, description="Final total amount charged to payment method")
    currency: str = Field(default="INR")
    destination_pincode: Optional[str] = None
    recurring: bool = False
    timestamp: str
    contract_id: str
    contract_version: Optional[int] = None
    merchant_policy_version: Optional[str] = None
    idempotency_key: Optional[str] = None


class BudgetState(BaseModel):
    total_budget_inr: float
    committed_spent_inr: float
    active_reserved_inr: float
    available_budget_inr: float
    requested_amount_inr: float
    budget_period: str


class AuthorizationDecision(BaseModel):
    """Structured decision trace generated by the Deterministic Authorization Firewall."""
    model_config = ConfigDict(from_attributes=True)

    decision_id: str
    transaction_id: str
    decision: DecisionEnum
    matched_rules: List[str]
    failed_rules: List[str]
    challenge_reasons: List[str] = Field(default_factory=list)
    policy_versions: Dict[str, Any]
    budget_state: BudgetState
    reason_code: str
    canonical_transaction: Dict[str, Any]
    agent_proposal: Optional[Dict[str, Any]] = None
    explanation: Optional[str] = None
    evaluated_at: str
